<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="1" name="matrix_tests.MatrixTest-20170408134454" skipped="0" tests="10" time="0.001">
	<testcase classname="matrix_tests.MatrixTest" name="testAttachMatrices" time="0.000"/>
	<testcase classname="matrix_tests.MatrixTest" name="testChangeRows" time="0.000"/>
	<testcase classname="matrix_tests.MatrixTest" name="testEchelonFormAndReducedEchelonForm" time="0.000"/>
	<testcase classname="matrix_tests.MatrixTest" name="testInvertMatrix" time="0.000"/>
	<testcase classname="matrix_tests.MatrixTest" name="testMatrixMultiplication" time="0.000"/>
	<testcase classname="matrix_tests.MatrixTest" name="testMultiplyRows" time="0.000"/>
	<testcase classname="matrix_tests.MatrixTest" name="testPrintMatrix" time="0.000"/>
	<testcase classname="matrix_tests.MatrixTest" name="testScalarMultiplication" time="0.000"/>
	<testcase classname="matrix_tests.MatrixTest" name="testTranspose" time="0.000"/>
	<testcase classname="matrix_tests.MatrixTest" name="testCountDeterminant" time="0.000">
		<failure message="12 != 4" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/home/hyttijan/MatrixCalculator/src/unittest/python/matrix_tests.py", line 53, in testCountDeterminant
    self.assertEqual(self.matrix2.countDeterminant(),4)
AssertionError: 12 != 4
]]>		</failure>
	</testcase>
	<system-out>
<![CDATA[[ 3  3  -15  9  ]
[ 1  0  -2  1  ]
[ 2  -1  -1  0  ]

]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
